spring.application.name=ecommerce

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=joRzzPxElg54muAyIMf57qrm6ArkvFuwUnD8Lji2gT2
jwt.expiration=86400000

payos.client-id=9106cce9-849f-4fba-8723-dc0a69f321ff
payos.api-key=8d3904df-2e22-4f85-bd60-42a9c3673157
payos.checksum-key=9bf1c064991c7db278f40fece18429aec8dd8186cf418667b39f442b7019ab6f